services:
  - type: web
    name: washtime
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://washtime_db_t5c1_user:nAFU92hqxSFQx74CvEIwCRXJrpWVUd4x@dpg-d61vaou3jp1c73eoqi80-a.oregon-postgres.render.com/washtime_db_t5c1
      - key: JWT_SECRET
        value: WashTime@2026SecureKey$RDK2305!JWT_prod
